[default]
bootstrap.servers=
security.protocol=
sasl.mechanisms=PLAIN
sasl.username=
sasl.password=

[producer]
# Low-latency batching: buffer messages for up to 5 ms before sending
linger.ms=5
# Wait for all in-sync replicas to acknowledge
acks=all
# Compress with lz4 for throughput with better compression ratio than snappy, but higher CPU cost
compression.type=lz4

[consumer]
group.id=
# 'auto.offset.reset=earliest' to start reading from the beginning of
# the topic if no committed offsets exist.
auto.offset.reset=earliest